### PR TITLE
Exception handling fixes

### LINKED ISSUE #48: Eliminate JSON checked exceptions
The Jackson JSON parsing library uses checked exceptions, which require catching and re-wrapping. This creates dozens of lines of extraneous stack trace in the log.

Alternatives:
* switch to a JSON libarary that doesn't use checked exceptions like Gson or Moshi
* Wrap Jackson's checked `JsonProcessingException` in a custom unchecked exception that doesn't create a new stack trace

### LINKED ISSUE #86: Cleanup all exceptions

### PR DESCRIPTION
**Pull request by chuck-dbos**
No "throws Exception"
Use Java built-in RuntimeException derivatives for programmer errors
Consistent DBOS exception naming
Use DB retry, and if it fails, system database is in bad shape and throw a (consistent) unchecked exception.

fixes #86 
fixes #48

### CODE REVIEW

File: src/main/java/dev/dbos/transact/exceptions/ErrorCode.java [hunk 1]
```diff
@@ -10,9 +10,8 @@ public enum ErrorCode {
   WORKFLOW_CANCELLED(7),
   UNEXPECTED_STEP(8),
   WORKFLOW_FUNCTION_NOT_FOUND(9),
-  SLEEP_NOT_IN_WORKFLOW(10),
-  RESUME_WORKFLOW_ERROR(11),
-  FORK_WORKFLOW_ERROR(12);
+  SYSTEM_DATABASE_ACCESS_ERROR(10),
```
Comment (devhawk) [inline src/main/java/dev/dbos/transact/exceptions/ErrorCode.java]: Does anything ever actually read this error code?

File: src/main/java/dev/dbos/transact/exceptions/DBOSAwaitedWorkflowCancelledException.java [hunk 2]
```diff
@@ -1,9 +1,9 @@
 package dev.dbos.transact.exceptions;
 
-public class AwaitedWorkflowCancelledException extends DBOSException {
+public class DBOSAwaitedWorkflowCancelledException extends DBOSException {
```
Comment (devhawk) [inline src/main/java/dev/dbos/transact/exceptions/DBOSAwaitedWorkflowCancelledException.java]: Why are we keeping this pattern for DBOS exceptions? (inheriting from DBOSException, including an error code even though the exception is strongly typed). This doesn't seem typical for Java codebases

File: src/main/java/dev/dbos/transact/execution/DBOSExecutor.java [hunk 3]
```diff
@@ -39,7 +39,6 @@
 import dev.dbos.transact.workflow.internal.WorkflowStatusInternal;
 
 import java.lang.reflect.InvocationTargetException;
-import java.sql.SQLException;
 import java.time.Duration;
```
Comment (devhawk) [inline src/main/java/dev/dbos/transact/execution/DBOSExecutor.java:41]: 🎉🎉🎉

**Review by devhawk — APPROVED** [review]
Other than the feedback on getting rid of `ErrorCode` and flattening the exception hierarchy, looks good

File: src/main/java/dev/dbos/transact/exceptions/DBOSAwaitedWorkflowCancelledException.java (hunk 2 above)
Comment (chuck-dbos) [reply src/main/java/dev/dbos/transact/exceptions/DBOSAwaitedWorkflowCancelledException.java]: Happy to try removing it... was certainly borrowed + we weren't all that terribly consistent with it.

File: src/main/java/dev/dbos/transact/json/JSONUtil.java [hunk 4]
```diff
@@ -39,7 +49,7 @@ public static String serializeArray(Object[] args) {
     try {
       return mapper.writeValueAsString(new Boxed(args));
     } catch (JsonProcessingException e) {
-      throw new RuntimeException("Serialization failed", e);
+      throw new JsonRuntimeException(e);
```
Comment (devhawk) [inline src/main/java/dev/dbos/transact/json/JSONUtil.java:52]: 🙏

File: src/main/java/dev/dbos/transact/database/SystemDatabase.java [hunk 5]
```diff
@@ -117,69 +120,83 @@ public void recordWorkflowOutput(String workflowId, String result) {
...
-
-    try {
-      try (Connection connection = dataSource.getConnection()) {
-        return StepsDAO.checkStepExecutionTxn(workflowId, functionId, functionName, connection);
-      }
-    } catch (SQLException sq) {
-      logger.error("Unexpected SQL exception", sq);
-      throw new DBOSException(UNEXPECTED.getCode(), sq.getMessage());
-    }
+      throws IllegalStateException, DBOSWorkflowCancelledException, DBOSUnexpectedStepException {
```
Comment (devhawk) [inline src/main/java/dev/dbos/transact/database/SystemDatabase.java]: Why are we declaring these? Their all runtime exceptions, right?

File: src/main/java/dev/dbos/transact/database/SystemDatabase.java [hunk 6]
```diff
@@ -107,7 +107,10 @@ public InsertWorkflowResult insertWorkflowStatus(
    * @param result output serialized as json
    */
   public void recordWorkflowOutput(String workflowId, String result) {
-    workflowDAO.recordWorkflowOutput(workflowId, result);
+    DbRetry.run(
```
Comment (devhawk) [inline src/main/java/dev/dbos/transact/database/SystemDatabase.java:110]: Do we need DbRetry on insertWorkflowStatus?

File: src/main/java/dev/dbos/transact/database/SystemDatabase.java (hunk 5 above)
Comment (chuck-dbos) [reply src/main/java/dev/dbos/transact/database/SystemDatabase.java]: In my defense, this diff was caused by an auto rename and those were already there :-)  Will fix.

File: src/main/java/dev/dbos/transact/database/SystemDatabase.java (hunk 6 above)
Comment (chuck-dbos) [reply src/main/java/dev/dbos/transact/database/SystemDatabase.java:110]: This is a bit tricky.  `insertWorkflowStatus` throws `SQLException` because it is being passed a connection with an open transaction.

Comment (chuck-dbos) [reply src/main/java/dev/dbos/transact/database/SystemDatabase.java:110]: In turn, `initWorkflowStatus` needs more help than I want to give it in this PR.
